# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='descriptions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='iframe_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='point_a',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='point_b',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
