# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160412_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='descriptions',
            new_name='description',
        ),
    ]
