# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160412_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='session',
            new_name='user_agent',
        ),
    ]
