# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160412_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='app.Connection'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='ip',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user_agent',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
