# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-13 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160516_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='iframe_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, null=True, upload_to=b'connects'),
        ),
    ]
