# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-14 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161013_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='iframe_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
