# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-27 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20161014_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b'connects'),
        ),
    ]
