# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-29 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20161027_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='connection_time',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connection',
            name='percent_more_than_2_transfer',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
